### ISSUE TITLE
项目源码问题

### ISSUE THREAD

**Issue by JackRo** [fanrunqi/FastScanCode#1]
您好，我亲自体验了一下这个项目的扫码速度，感觉非常棒，可是好像还是有一些问题，比如如果离的距离远了或者光线暗了，条码解析会出错。
当然我不是针对这些问题，我主要想说的是：能否把扫码的源码开源出来呢？而不是放一个aar包。这样感兴趣的人也可以一起参与进来，维护这个非常棒的项目。

**Comment by fanrunqi** [comment]
因为涉及到公司内部项目，所以...
